language: c

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make

matrix:
  include:
    - name: Linux arm
      os: linux
      arch: arm64
      compiler: gcc

    - name: Linux amd64
      os: linux
      arch: amd64
#    - name: Power ppc64le
#      os: linux-ppc64le
#      compiler: gcc     

